### ISSUE TITLE
Error at ES5

### ISSUE THREAD

**Issue by roovenier** [shane-tomlinson/node-font-face-generator#14]
Hi @shane-tomlinson

In the latest version of your package I get an error, because it doesn't work with Node.js ES5 and lower:

> /Users/alex/myapps/fonsta/node_modules/node-font-face-generator/node_modules/node-uap/index.js:8
>     ].find(fs.existsSync),
>       ^
> TypeError: undefined is not a function
>     at Object.<anonymous> (/Users/alex/myapps/fonsta/node_modules/node-font-face-generator/node_modules/node-uap/index.js:8:7)
>     at Module._compile (module.js:460:26)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Module.require (module.js:365:17)
>     at require (module.js:384:17)
>     at Object.<anonymous> (/Users/alex/myapps/fonsta/node_modules/node-font-face-generator/lib/generate_css.js:11:26)
>     at Module._compile (module.js:460:26)
>     at Object.Module._extensions..js (module.js:478:10)

Please fix it :)

**Comment by shane-tomlinson** [comment]
Thanks for the feedback @roovenier. What version of node are you using? From the trace, that looks like a problem with node-uap that I have no control over. :(

**Comment by roovenier** [comment]
I'm using 0.12.7 version of node.
Yes, problem with node-uap. Unfortunately this package doesn't provide compatibility with previous node versions by not using polyfill.
Anyway I stayed on version 0.1.5 and it works fine.
